### ISSUE TITLE
[suggestion] Have an way to archive an message.

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [AnimeKaizoku/SibylSystem#14]
It should have a way to archive messages, both from auto-scans, when `?scan` is triggered, and when pajeets triggered `/report` or called the `@admins` to a designated chat (can be different from the base chat where forced scans, manual scans, approvals and denials are happens). We can also manually archive an message by having a `log` command in the userbot.

The only problem is how about NSFW or CACP stuff. How we censor the media that contains NSFW/CACP crap?

**Comment by DragSama** [comment]
I don't know how `log `command will be useful since it logs message anyway when scanned

**Comment by Dank-del** [comment]
@DragSama You're high, go sleepu

**Comment by AndreiJirohHaliliDev2006** [comment]
> I don't know how `log `command will be useful since it logs message anyway when scanned 

@DragSama We can log messages if the userbot operator think that the message might have nit enough evidence or maybe it's potentially spam but can't be verified.

**Comment by TsunayoshiSawada** [comment]
@AndreiJirohHaliliDev2006 No such case.
Scans are always verified
