### ISSUE TITLE
Print login code when an new code received in console + "!sibyl otp" command

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [AnimeKaizoku/SibylSystem#32]
## Problem
When I tried to do `!ssc exec print((await event.client.get_messages(777000, 1))[0].text)` (that's for my fork, in general: `!sibyl exec print((await event.client.get_messages(777000, 1))[0].text)`) send me the code, but the problem is I get the `Code invalid, please login again` error.

## Suggestion
Whenever the new login code is received, the console log should print like this:

```
YYYY-MM-DD HH:MM:SS,MSS - Sibyl_System.otpDetector - INFO - New login code detected, your code is: 12345
```

Just in case the userbot is in Heroku or via an VPS and can't do `ssh tg-userbots@ssh.animekaizoku.com  "cat ~/SibylSystem/log.txt"`, a handy command called `!sibyl otp` should be used. When triggered, the response message should looks like this:

```py
otpCode = """
Hey {Enforcer} {name},

Your OTP code to log into the userbot is 12345, and will expire after 10 minutes if unused.
"""
```

**Comment by AndreiJirohHaliliDev2006** [comment]
Btw, `12345` should be inside `{}`.

**Comment by TsunayoshiSawada** [comment]
@AndreiJirohHaliliDev2006 I doubt drag will implement this as the point of sibyl is stability on our server, which it is.

**Comment by DragSama** [comment]
> When I tried to do !ssc exec print((await event.client.get_messages(777000, 1))[0].text) (that's for my fork, in general: !sibyl exec print((await event.client.get_messages(777000, 1))[0].text)) send me the code, but the problem is I get the Code invalid, please login again error.

That code will just send the latest message from telegram, If It's invalid, You are doing something wrong (You are using wrong number or Sibyl is not on the same number or You are entering wrong code).

> !send otp

Sibyl is not a multipurpose userbot, It aims at protection against spam. I don't think adding this command will help in that.

Closing since I don't think this has anything to do with Sibyl.
