### ISSUE TITLE
Switch to pyrogram

### ISSUE THREAD

**Issue by mozzic** [AnimeKaizoku/SibylSystem#33]

**Comment by DragSama** [comment]
No

**Comment by mozzic** [comment]
Why not??

**Comment by DragSama** [comment]
Why should I?

**Comment by Dank-del** [comment]
@mozzic You can make one yourself, contribute to open source software. :D

**Comment by mozzic** [comment]
Pyrogram has faster downloads and uploads

**Comment by Dank-del** [comment]
@mozzic We don't need those here.

**Comment by DragSama** [comment]
> Pyrogram has faster downloads and uploads
Seems legit. I forgot I used Sibyl System to download 2gb movies

**Comment by mozzic** [comment]
> @mozzic You can make one yourself, contribute to open source software. :D

I don't know python

**Comment by lsoQS** [comment]
@mozzic

**Comment by Dank-del** [comment]
@mozzic Then don't open issues on something you don't understand.

**Comment by mozzic** [comment]
> @mozzic Then don't open issues on something you don't understand.

Why not? I'm just saying switching to pyrogram will make it better

**Comment by DragSama** [comment]
> > @mozzic Then don't open issues on something you don't understand.
> 
> Why not? I'm just saying switching to pyrogram will make it better

Define better.

**Comment by mozzic** [comment]
> > > @mozzic Then don't open issues on something you don't understand.
> > 
> > 
> > Why not? I'm just saying switching to pyrogram will make it better
> 
> Define better.

Pyrogram is easier

**Comment by DragSama** [comment]
> > > > @mozzic Then don't open issues on something you don't understand.
> > > 
> > > 
> > > Why not? I'm just saying switching to pyrogram will make it better
> > 
> > 
> > Define better.
> 
> Pyrogram is easier

If you don't know Python, How do you know Pyrogram is easier ?

**Comment by Dank-del** [comment]
@mozzic I repeat, don't nose into something which you have no idea about, pyrogram may be easier but we don't need it for this project
